In [2]:
import pandas as pd
df = pd.DataFrame({'val':[10,20,30]}, index=['a','b','c'])
print(df)


   val
a   10
b   20
c   30


In [5]:
print(df.loc['a':'b'])
print()
print(df.iloc[0:2])

   val
a   10
b   20

   val
a   10
b   20


In [10]:
import numpy as np

r,c = map(int, input("Enter rows and columns: ").split())
print("Enter Matrix A:")
aa = []

for i in range(r):
    row = list(map(int, input().split()))
    aa.append(row)
    
A = np.array(aa)
print(A)

print("Enter Matix B:")
bb = []


for i in range(r):
    row = map(int, input("Enter rows and columns: ").split())
    bb.append(row)

B = np.array(bb)
print(B)



Enter Matrix A:
[[20 30]
 [20 30]
 [10 20]]
Enter Matix B:
[<map object at 0x0000020828AE2AC0> <map object at 0x0000020845BC1E80>


In [ ]:
import numpy as np
l = list(map(int, input().split()))

arr = np.array(l)
print(arr)

r, c = map(int, input().split())
new_arr = arr.reshape(r, c)
print("Reshaped array: \n", new_arr)                                               

[1 2 3 4 4 5]
Reshaped array: 
 [[1 2 3]
 [4 4 5]]


In [22]:
import pandas as pd
l = list(map(int, input().split()))
s = pd.Series(l, index=[1,2,3,4,5,6])
print("Series:\n", s)
print("Max value:", s.max())
print("Index of max value:", s.idxmax())


Series:
 1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64
Max value: 6
Index of max value: 6


In [33]:
import pandas as pd 
data = {
    "Region": ["N", "N", "N", "S", "S", "S"],
    "Category": ["A","A","B","B","B","A"],
    "Sales": [100,200,350,250,150,200]
}
df = pd.DataFrame(data)

df.groupby(["Region"]).agg(avg_sales = ("Sales","mean"), total_revenue = ("Sales","sum"))

,avg_sales,total_revenue
Region,,
N,216.666667,650
S,200.000000,600
